# Generated by Django 4.1.1 on 2022-10-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VooBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_voo', models.CharField(max_length=200)),
                ('compania_aerea', models.CharField(max_length=200)),
                ('dia_da_semana', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terca'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sabado'), ('DOM', 'Domingo')], max_length=3)),
                ('horario_partida_base', models.TimeField(null=True)),
                ('duracao_base', models.CharField(max_length=200)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'voo_base',
            },
        ),
        migrations.CreateModel(
            name='VooReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voo', models.DateField()),
                ('estado_voo', models.CharField(choices=[('EMB', 'Embarcando'), ('CAN', 'Cancelado'), ('PRG', 'Programado'), ('TAX', 'Taxiando'), ('PRT', 'Pronto'), ('AUT', 'Autorizado'), ('EMV', 'Em voo'), ('ATE', 'Aterrisado')], max_length=3)),
                ('horario_real_chegada', models.TimeField(null=True)),
                ('horario_real_partida', models.TimeField(null=True)),
                ('voo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voobase')),
            ],
            options={
                'db_table': 'voo_real',
            },
        ),
    ]
