# Generated by Django 4.1.1 on 2022-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voobase',
            old_name='compania_aerea',
            new_name='companhia_aerea',
        ),
        migrations.AlterField(
            model_name='voobase',
            name='duracao_base',
            field=models.IntegerField(),
        ),
    ]
