# Generated by Django 4.1.1 on 2022-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_compania_aerea_voobase_companhia_aerea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voobase',
            name='horario_partida_base',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vooreal',
            name='estado_voo',
            field=models.CharField(choices=[('AGD', 'Agendado'), ('EMB', 'Embarcando'), ('CAN', 'Cancelado'), ('PRG', 'Programado'), ('TAX', 'Taxiando'), ('PRT', 'Pronto'), ('AUT', 'Autorizado'), ('EMV', 'Em voo'), ('ATE', 'Aterrisado')], max_length=3),
        ),
    ]
