# Generated by Django 4.1.1 on 2022-11-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vooreal_horario_real_chegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vooreal',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vooreal',
            name='voo_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voobase'),
        ),
    ]
