# Generated by Django 4.1.1 on 2022-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vooreal_id_alter_vooreal_voo_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='estado_voo',
            field=models.CharField(choices=[('AGD', 'Agendado'), ('PRG', 'Programado'), ('EMB', 'Embarcando'), ('TAX', 'Taxiando'), ('PRT', 'Pronto'), ('AUT', 'Autorizado'), ('EMV', 'Em voo'), ('ATE', 'Aterrisado'), ('CAN', 'Cancelado')], max_length=3),
        ),
    ]
